CREATE TYPE "level" AS ENUM (
  'principiante',
  'medio',
  'avanzando'
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "age" int
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "title" varchar NOT NULL,
  "description" text NOT NULL,
  "level" level,
  "teacher" varchar,
  "id_category" int NOT NULL
);

CREATE TABLE "course_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "title" varchar NOT NULL,
  "url" varchar NOT NULL,
  "id_course" int NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL
);

CREATE TABLE "users_course" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "id_user" int NOT NULL,
  "id_course" int NOT NULL
);

ALTER TABLE "users_course" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("id");

ALTER TABLE "users_course" ADD FOREIGN KEY ("id_course") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("id_category") REFERENCES "categories" ("id");

ALTER TABLE "course_videos" ADD FOREIGN KEY ("id_course") REFERENCES "courses" ("id");


insert into users ("name",
email,
"password",
age)values('rafael',
'rafael@gmail.com',
'root',
32);

insert into users ("name",
email,
"password",
age)values('adrian',
'adrian@gmail.com',
'root',
32);
 
insert into categories ("name") values ('react'); 
insert into categories ("name") values ('node'); 

insert into courses (title,
description,"level",
teacher,
id_category) values('hooks','lorem','principiante','benjamin',1);



insert into courses (title,
description,"level",
teacher,
id_category) values('sql','lorem','principiante','sahid',1);

insert into users_course (id_user,id_course) values (1,1);
insert into users_course (id_user,id_course) values (2,2);


insert into course_videos (title,url,id_course) values('hooksvideo','lorem',1);
insert into course_videos (title,url,id_course) values('dqlvideo','lorem',2);
